{% set version = "1.13.2" %}
{% set build = 1007 %}

# recipe-lint fails if mpi is undefined
{% set mpi = mpi or "nompi" %}
{% if mpi == "nompi" %}
# prioritize nompi via build number
{% set build = build + 100 %}
{% endif %}

package:
  name: h5utils
  version: {{ version }}

source:
  url: https://github.com/NanoComp/h5utils/releases/download/{{ version }}/h5utils-{{ version }}.tar.gz
  sha256: eea7855a8235facb7c454e61103098e55658da0ddf4b6de5b82a992e5f024351

build:
  number: {{ build }}
  skip: true  # [win]
  {% if mpi != "nompi" %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  # add build string so packages can depend on
  # mpi or nompi variants
  # dependencies:
  # `h5utils * mpi_mpich_*` for mpich
  # `h5utils * mpi_*` for any mpi
  # `h5utils * nompi_*` for no mpi
  string: "{{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}"
  run_exports:
    - h5utils * {{ mpi_prefix }}_*

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - make
    - pkg-config
  host:
    - {{ mpi }}  # [mpi != 'nompi']
    - libpng
    # We need to list hdf5 twice to get version pinning from
    # conda_build_config.yaml, (which falls back to the one from conda-forge,)
    # and build pinning from {{ mpi_prefix }}
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
    - zlib
    - numpy
  run:
    - {{ mpi }}  # [mpi != 'nompi']

test:
  requires:
    - h5py
    - numpy
  commands:
    - h5topng -h
    - h5totxt -h
    - h5fromtxt -h
    - h5tovtk -h

about:
  home: https://github.com/NanoComp/h5utils
  license: MIT
  license_file: COPYING
  summary: A set of utilities for visualization and conversion of scientific data in the free portable HDF5 format
  doc_url: https://github.com/NanoComp/h5utils/tree/master/doc
  dev_url: https://github.com/NanoComp/h5utils

extra:
  recipe-maintainers:
    - oskooi
